### ISSUE TITLE
Week April 1 to-do

### ISSUE THREAD

**Issue by amarchenko26** [amarchenko26/metoo#1]
- [x] make balance table / data description table 
- [x] Do something with the treat variable - run a simple DID with the relief var. 
- [x] Run a DiD according to my different specifications. 
- [x] pick a good control group of case types 
- [x] restrict to employment ONLY - most salient. 
- [x] make a balancetable of case characteristics that end right before and right after MeToo 
- [ ] to figure out change in probability, run regression of P(win) = 1.(if case ended after vs. if case ended before) + length of case + chars

**Comment by amarchenko26** [comment]
- [ ] Do a falsification / check where effects shouldn't show up.

**Comment by amarchenko26** [comment]
- [ ] check if duration between filing and resolution is correlated w rpobability of winning or compensation -- we dont want it to be the case that more severe cases take longer and are also more likely to win or get damages

**Comment by amarchenko26** [comment]
- [ ] add code that deletes and recreates folders in run_project.do
