### ISSUE TITLE
Week April 8 to-do

### ISSUE THREAD

**Issue by amarchenko26** [amarchenko26/metoo#2]
- [ ] Put figure 1 into different axes, or take logs
- [ ] plot relief by SH and non-SH over time
- [ ] cluster p-values in balance table
- [ ] Run DiD - for employment only
- [ ] add code that deletes and recreates folders in run_project.do
- [ ]  to figure out change in probability, run regression of P(win) = 1.(if case ended after vs. if case ended before) + length of case + chars

**Comment by amarchenko26** [comment]
- [ ] Create a binscatter version of the compensation figure!!
